### ISSUE TITLE
Dynamic view linked in docs throws error in playground

### ISSUE THREAD

**Issue by deinspanjer** [likec4/likec4#1009]
On the doc page https://likec4.dev/dsl/dynamic-views/ at the bottom, it has a link to the playground URL:
https://playground.likec4.dev/w/dynamic/

The first several times I clicked that link using latest stable of Firefox, I got a rendering error:

![image](https://github.com/user-attachments/assets/49dfb64c-648b-4318-96c7-d6083e60c182)

When I tried it again after starting this report, it rendered, but since I had already grabbed all the details, I figured I'd go ahead and report in case it is something you can track down as a systemic problem.

**Comment by davydkov** [comment]
Hey @deinspanjer 

For me this seems pure flaky, network related issue.
Or is it reproducible for you?

**Comment by davydkov** [comment]
I close this issue, let us know if it still exists
