### ISSUE TITLE
VS code formatter adds an extra space in dynamic view

### ISSUE THREAD

**Issue by jentor** [likec4/likec4#1056]
Hello! 
Thanks for cute and handy tool!

I need a little guidance with VS Code formatter that breaks **dynamic views** with extra space when source element specified as nested (system.element -> ...).  

**Example**
```
coordinator -> cloud.redis '[ req.stream : write ] \n Puts a new job'
cloud .redis -> splatting '[ req.stream : read ] \n Fetches a job to execute'
```

After formatting there is always arise a space between 'cloud' and '.redis' that breaks everything.
And affected side is always `source` (X ->) , not `target` (-> X).

**Comment by pavelpykhtin** [comment]
Hi, @jentor !

Thank you for your feedback!
