### ISSUE TITLE
Model elements could include external components from other models

### ISSUE THREAD

**Issue by cisasmendi** [likec4/likec4#106]
Model elements could include external components from other models, I can't figure out how or if documentation is missing

**Comment by davydkov** [comment]
Thank you for your ideas!
You are right. Documentation is still an ongoing process.

I am not sure I understood you clearly regarding this issue.

In LikeC4, the workspace files unite and create like a global model.
Can you please check [this page](https://likec4.dev/docs/dsl/workspace/)? Is it what you mean?
