### ISSUE TITLE
Make Kroki URL configurable

### ISSUE THREAD

**Issue by fkhoda** [likec4/likec4#1060]
Hi,

Is it possible to make the Kroki URL configurable in [here](https://github.com/likec4/likec4/blob/3201a2bf6b89e603ff000bd8b0c72f0d3e85ffd5/packages/likec4/app/src/routes/view.%24viewId.d2.tsx#L26)? For example this could work by passing a new argument to the CLI and/or an environment variable?

This is blocking us from using this in a secure/work environment :(

Thanks a lot!

**Comment by davydkov** [comment]
@fkhoda in 1.12 release can be changed with environment variable

```
VITE_KROKI_D2_SVG_URL='https://your-kroki/' likec4 start
```
