### ISSUE TITLE
Unable to open diagram from Sidebar

### ISSUE THREAD

**Issue by aelberg** [likec4/likec4#1091]
After upgrading to 1.12.1 I am unable to open a diagram using the sidebar using any of the grouping options.  I tested in Chrome and Edge.
I liked the Folder grouping that was default in prior versions so am looking forward to this feature!

**Comment by davydkov** [comment]
Hey @aelberg, thanks for reporting
Fixed in [1.12.2](https://github.com/likec4/likec4/releases/tag/v1.12.2), releasing now
