### ISSUE TITLE
Bundled Azure icons vary in color scheme

### ISSUE THREAD

**Issue by vedeja** [likec4/likec4#1097]
Using 1.12.2 and the bundled Azure icons, their color scheme seems to change from view to view. Even for the same model element.

`icon azure:application-gateways`
![image](https://github.com/user-attachments/assets/48a79445-ded7-4f21-a525-8d0e8d2b1d24)
![image](https://github.com/user-attachments/assets/3e91a04c-5536-44c5-a1f9-bd41ca14373e)

`icon azure:app-services`
![image](https://github.com/user-attachments/assets/7259caff-41d5-433f-972c-427cd3c0952e)
![image](https://github.com/user-attachments/assets/10644ea2-5560-4912-b403-f534cd23a370)

**Comment by davydkov** [comment]
Hey @vedeja 
Could you verify in v1.13?

**Comment by vedeja** [comment]
@davydkov It appears that it is the same problem in 1.13

**Comment by pavelpykhtin** [comment]
@davydkov , linearGradient is defined in defs section of svg and thus is scoped to the whole document rather than that particular image. Added fix with unique suffix to defs content.
