### ISSUE TITLE
Navigate chart without opening a new modal

### ISSUE THREAD

**Issue by luciob** [likec4/likec4#1112]
Hello, I like very much your project and looking forward to include it in our tool.
I'm starting to integrate it in a NextJS app, using the `codegen ts` command.

I was wondering if there's a way to navigate the C4 chart without opening a new modal.
I saw this behaviour is driven by the `interactive` prop, but if I disable it, the charts remains fully static.
What I'd like to achieve is showing the nested levels (or details) of a building block inside the same space reserved to the `index` view, and use your sidebar for chart navigation (e.g. going back to the root level).

I attach a screen to explain the situation of what I'm trying to achieve when clicking on the magnifying-glass icon:

<img width="890" alt="Screenshot 2024-10-16 at 16 30 00" src="https://github.com/user-attachments/assets/419e05ac-7845-4206-a6a3-052a7908da7d">

Thank you

**Comment by davydkov** [comment]
Can you try this?

```tsx
import { ReactLikeC4, type LikeC4ViewId } from './generated'

function LikeC4() {
  const [viewId, setViewId] = useState<LikeC4ViewId>('index')

  return <ReactLikeC4 viewId={viewId} onNavigateTo={setViewId}/>
}

```

**Comment by luciob** [comment]
> Hey @luciob, can you try this?
> 
> ```tsx
> import { ReactLikeC4, type LikeC4ViewId } from './generated'
> 
> function LikeC4() {
>   const [viewId, setViewId] = useState<LikeC4ViewId>('index')
> 
>   return <ReactLikeC4 viewId={viewId} onNavigateTo={setViewId}/>
> }
> ```

Thanks, works great.
