### ISSUE TITLE
does not render long description texts using available space

### ISSUE THREAD

**Issue by mind6** [likec4/likec4#1227]
Thank you for writing this software. I really like the ability to zoom in and out and using domain specific elements. I'm trying to dig into the "code" level which isn't supported in Structurizr. Instead of using UML or Mermaid, I want to use LikeC4 to sketch out what classes look like once you're down to this level.  This means I need to fully describe the public interface of each code or class element. I experimented with using an element to represent each field or method, but they were taking too much space. I found it was enough to simply put the interface in the description property, for example
```c4
specification {
   element class
}
model {
   class MyClass {
      description "
         prop1: String - describes first property
         prop2: Int
         prop3: Int
         prop4: Int
         prop5: Int
         prop6: Int
         prop7: Int
         prop8: Int
         prop9: Int
         method1: Float - first accessor method
         method2: Float
         method3: Float
         method4: Float
         method5: Float
         method6: Float
      "
   }
}
views {
   view of MyClass {
      include *
   }
}
```

I'm not looking for fancy formatting, to me the best part of LikeC4 is the automatic layout, navigation, and zooming, so you always have a multi-level map of the context and details. 

Currently in LikeC4 v1.16.0, the default rendering allocates space based on the long description text, but only the center part of the rectangle is used:

![image](https://github.com/user-attachments/assets/008ad79b-981c-4737-9d0e-bbb23e590b5e)

The box grows as I add more text, but only the same amount of text is rendered.

Would it be possible to fix this rendering issue? Or is this an unintended use of the description property? I would like to be able to visualize a large amount of details when needed, even though most of the time the description should be short.

**Comment by davydkov** [comment]
Hey @mind6 

I hope [v1.17.0](https://github.com/likec4/likec4/releases/tag/v1.17.0) has resolved the issue.

And I think it would be great to introduce a specific shape for such cases in the future.
