### ISSUE TITLE
Predicate to include all descendants `.**`

### ISSUE THREAD

**Issue by davydkov** [likec4/likec4#1259]
I've been thinking about possible options for such a predicate. Glob patterns use `**` for this purpose. Thus `saas.**` would include all descendants of `saas`. Is there any technical reason for why this should not exist? If not, I'd like to give implementing it a shot.

_Originally posted by @Cyclonit in https://github.com/likec4/likec4/discussions/1114#discussioncomment-11361687_

**Comment by Cyclonit** [comment]
Hi @davydkov,

I am (slowly) working my way through the language definition and how the parsing works. If I understand everything correctly, `*` on "root" level and `element.*` are two fundamentally different constructs. One is a so called "wildcard" and the other sets the flag `ElementRef.isDescendants`. I will focus on the later for now, but I have a question regarding the former.

According to [/apps/docs/src/content/docs/dsl/views.mdx:160+](https://github.com/likec4/likec4/blob/main/apps/docs/src/content/docs/dsl/views.mdx?plain=1#L169) `*` behaves differently when used inside a `view` compared to a `view of`. To me, it looks like the behavior in `view of` is exactly what `**` is supposed to achieve in the future. Would it make sense to introduce a top level `**`, that behaves like `*` for scoped views, but works for both scoped and unscoped views? At that point, `*` and `**` would both work in scoped views. A second (albeit breaking) change would be to change `*` in scoped views to behave exactly like it does in unscoped views.

Example:
```
views {
  // old: include all top level elements
  view {
    include *
  }
  // new: include all top level elements and their descendants -> all elements
  view {
    include **
  }
  // old: include cloud.ui and all of its descendants
  view of cloud.ui {
    include *
  }
  // new: include cloud.ui and all of its descendants
  view of cloud.ui {
    include **
  }
}
```

On a side note, I would rename `isDescendants` to `isChildren`, such that `isDescendants` is available for the new selector. Would there be any reason not to do that?

**Comment by davydkov** [comment]
> looks like the behavior in `view of` is exactly what ** is supposed to achieve in the future. 

`view of smth` has several semantics.
First, inside scoped views predicate `include *` becomes like:
```zig
include smth
include smth.* // includes only children
include -> smth.* -> // includes incoming to/outgoing from "outside" of smth
```
Second - a scoped view inherits the “scope” of the associated element.
Third - the scoped view becomes the default for the element.

I’m skeptical about introducing a predicate `include **` without further exploration of its use cases.
As a first step, I suggest focusing on `.**` only.

> On a side note, I would rename `isDescendants` to `isChildren`, such that `isDescendants` is available for the new selector. Would there be any reason not to do that?

I don’t see any immediate issues, though this change might have a broader impact.
Perhaps my comment https://github.com/likec4/likec4/discussions/1114#discussioncomment-11361784 could be a good starting point and we support `.**` iteratively?
This is just an initial idea—I’m not insisting it’s the right one.

<details>

<summary>And another idea for Langium</summary>

What if we change line 378
https://github.com/likec4/likec4/blob/dc0224b8984889ea7ba304378af6dbb2b80a83f8/packages/language-server/src/like-c4.langium#L375-L379
to
```
 {infer ElementDescedantsExpression.parent=current} suffix=DotWildcard 
```
And terminal `DotWildcard`
```
terminal DotWildcard: /\b\.\*{1,2}/;
```
Now, when we parse `ast.ElementDescedantsExpression` check value of `suffix`: `.**` for all nested and `.*` for children onlyt

</details>

**Comment by Cyclonit** [comment]
I apologize if I am asking stupid questions, but this is the first time I am contributing to a project of this kind I don't understand everything. Why does [`LikeC4ModelGraph.childrenOrElement(id: Fqn)`](https://github.com/likec4/likec4/blob/e5cd635fdb99d83952c1d0abee66ffdcf855783a/packages/language-server/src/model-graph/LikeC4ModelGraph.ts#L104) return the children OR the node itself? There is only one place calling that method in `predicates.ts`, and from my testing it looks like that method does not care if the list includes the node itself alongside the children or other descendants. Excluding the node itself if it has descendants appears to be unnecessary.

**Comment by Cyclonit** [comment]
I have another question. Currently `.*` is treated as a property of the `ElementRef` and thus cannot be chained. Should we consider supporting scenarios like `a.*.*` in the future?

**Comment by davydkov** [comment]
Hey @Cyclonit 

Apologies for the delayed response.

>  Currently .* is treated as a property of the ElementRef and thus cannot be chained

I must admit that this turned out to be a bad experience.
Instead, I use another approach for deployments:

https://github.com/likec4/likec4/blob/fabc79ffc777f1a0ce1b4afe304c10a970c04759/packages/language-server/src/like-c4.langium#L617-L619

> Should we consider supporting scenarios like a.*.* in the future?

I believe yes, and it might look like this:

```langium
 DeploymentRefExpression: 
   ref=DeploymentRef suffixes+=(DotUnderscore | DotWildcard)*
 ;
```
Though, not sure if this works with current terminals.
I suggest you keep it out of scope.

Don’t hesitate to ask any questions; I’m happy to help.
Later I organize some communication channels, for now you reach me at https://t.me/denchieek
