### ISSUE TITLE
azure icons are not supported in vscode

### ISSUE THREAD

**Issue by joshendriks** [likec4/likec4#1320]
Use of azure icons leads to an incomplete render in vscode while `likec4 serve` renders properly.

Example c4 file to reproduce:
```
specification {
  element thing
}

model {
  something = thing "Event queue" "Azure Service Bus"{
    icon azure:azure-service-bus
  }
  somethingElse = thing "Other queue" "Azure Service Bus"{
    icon tech:rabbitmq
  }
}

views {
  view index {
    title 'Landscape'
    include *
  }
}
```

Result in browser:
<img width="458" alt="image" src="https://github.com/user-attachments/assets/0f6880c2-cb5a-4f1d-9075-40b163073d48">

Result in vscode preview:
<img width="502" alt="image" src="https://github.com/user-attachments/assets/de34ae79-a655-47f6-a3f2-9b91e691345d">

Leaving out line `icon azure:azure-service-bus` gives a better result in the vscode preview:
<img width="466" alt="image" src="https://github.com/user-attachments/assets/808e50cc-bdde-4aa5-b0c4-cf3a4b2130ed">

Note that the vscode preview is not only is missing the icon, but also other elements are not rendered. Personally I do not care that much about the icon during editing. The preview not being complete is the real issue.

My proposal is to solve this by allowing icons to fail. I.e. make `icon azure:azure-service-bus` a warning and skip that line for rendering so that I at least get to see the full diagram.

System information:
MacOs 15.1.1
Vscode 1.88.0
LikeC4 vscode extension v1.6.1
Npm 9.8.1
node 18.18.0 (under nvm 0.39.7)
gobally installed likec4 1.17.1

**Comment by Cyclonit** [comment]
I cannot reproduce this on my machine.

Windows 10
VS Code 1.95.3
LikeC4 VS Code extension v1.17.1
Node 20.18.0

**Comment by joshendriks** [comment]
You VScode version triggered me to update mine as well. I now have vscode version: 1.95.3. That resolved it.
