### ISSUE TITLE
Allow carriage return in title and description

### ISSUE THREAD

**Issue by Kiiv** [likec4/likec4#1324]
Hi,

I'm trying to add a carriage return in a title to have something on two lines.
I've tried :
```
"first line\nsecond line"
```
 and 
```
"first line<br>second line"
```
 but it does not work.

Is there a way to achieve this or is it possible to implement it ?

**Comment by davydkov** [comment]
Release [1.18](https://github.com/likec4/likec4/releases/tag/v1.18.0)
