### ISSUE TITLE
Error generating png behind proxy

### ISSUE THREAD

**Issue by hexstyle** [likec4/likec4#1374]
When publishing png `npm run export:png`, there is no way to specify a proxy server.
That's why the error occurs when exporting PNG during an external resource request: https://cdnjs.cloudflare.com/polyfill/v3/polyfill.min.js

> TimeoutError: page.goto: Timeout 10000ms exceeded

There are 2 solutions:
1. Use the NPM polyfill package instead of linking to an external cdn
2. Add the proxy parameter to the Cli

**Comment by davydkov** [comment]
@hexstyle Thank you for reporting!

I removed polyfills; they appear to be unnecessary (unless someone is using Internet Explorer 11).
