### ISSUE TITLE
Display technology on card

### ISSUE THREAD

**Issue by ScottSlaughterBBNA** [likec4/likec4#208]
There is a Technology property that does not display in the views currently. It would be good if that displayed or if there were a way to conditionally turn on display of that property.

**Comment by davydkov** [comment]
Hey @ScottSlaughterBBNA, [v0.30.0](https://github.com/likec4/likec4/releases/tag/v0.30.0) includes this feature. Can you please validate?

Also, I want to discuss and get feedback.

The idea is to define a kind of "dictionary" of technologies, like:

```
specification {

  technology lambda
  technology Java
  technology node 'NodeJS' // title to display
  technology grpc

}

model {

  bpm = app 'Business Process Manager' {
    technology: Java, grpc;
  }

  onNewUser = lambda 'Listerner OnNewUser Workflow' {
    technology: lambda, Node;

    -> bpm 'triggers OnNewUser workflow' {
      technology: grpc; // what technology is used for communication.
                        // both ends of the relationship, `bpm` and `onNewUser`,
                        // have this technology implicitly (or must include?)
    }
  }

}
```

Benefits:

1. References in IDE, what elements/relationships use some particular technology
2. Use as view predicate
3. Generate TechRadar?

(1, 2) can be solved with already existing tags, but not 3.
On another hand, it sounds like over-complication, does not it?
Does likec4 require to define technology always or maybe:

```
model {

  bpm = app 'Business Process Manager' {
    technology: 'Some BPM Server'; // shown on a card
    technologies: Java, grpc;      // used for references
  }

```

What do you think? What is your usecase for technology label?

**Comment by ScottSlaughterBBNA** [comment]
As anything in a document like this, it's all about the discussion and decision tracking. I think labeling the technology on a model object is useful for the discussion, and once a decision is made having that attribute on the model object is good when someone eventually comes looking to see what was done. I think a decision documentation system is more useful for the details involved. I like the idea of defining the technologies in the spec and then applying them throughout the model just for consistency. Perhaps it could be useful for searching for locations where specific technologies are used at some point. But I'm not sure I have a specific use case for that currently. 

I have pulled 0.30.0 and everything appears to be working for displaying the value in the technology parameter.
