### ISSUE TITLE
Cli error when designating a path

### ISSUE THREAD

**Issue by ScottSlaughterBBNA** [likec4/likec4#212]
I was not able to get likec4 to run as a command, so I've had to run it through node. I'm not sure if that would yield different results. But any attempt I make to run codegen for react where I'm passing in a path to the model files fails. It appears to be appending the path onto itself 3 times and than failing the find that string as a path.

As an example the command "node ./node_modules/@likec4/cli/likec4.js codegen react -o test.tsx c:/projects/" yields:

![image](https://github.com/likec4/likec4/assets/136729466/eef36e2c-64b8-4170-bfba-583c45eac3bb)

But browsing into the correct directory and running "node ./node_modules/@likec4/cli/likec4.js codegen react -o ." works just fine.

**Comment by davydkov** [comment]
Nice catch, I did not test on Win.

I think I know the cause, gonna check and update you soon

**Comment by davydkov** [comment]
I release new version to check on Win
