### ISSUE TITLE
React Component View Switching and animation

### ISSUE THREAD

**Issue by ScottSlaughterBBNA** [likec4/likec4#220]
Is the generated React component intended to be a static displayed image, or interactive like the VS Code plugin? I've generated a component, but it seems to be stuck on the index view. I've tried the pannable and zoomable properties which both work. I've also tried the animate property, which doesn't appear to be functioning. I think that may be my problem, but I'm not getting any errors. 

The diagram is displaying and I can pan and zoom. Double clicking the diagram resizes and centers, so that appears to be working without issue.

**Comment by davydkov** [comment]
@ScottSlaughterBBNA just noticed this one 😃 

Yes, be honest, React Diagrams are not complete yet, the [interactive mode](https://github.com/likec4/likec4/blob/e478fb27a0ce9e635fef4f8afb0f7bcf5e2cb4d1/docs/components/index-page/LikeC4Diagram.tsx#L90-L106) exists only inside the docs project, and I have not ported it back yet, still experimenting 🏗️

**Comment by ScottSlaughterBBNA** [comment]
Yea, I figured. I got it doing what I need it to for now, so I closed the issue. Thanks.
