### ISSUE TITLE
Azure DevOps Build codegen issue

### ISSUE THREAD

**Issue by ScottSlaughterBBNA** [likec4/likec4#231]
I tried to run the react codegen in an Azure DevOps build pipeline and received some odd output. It validated the .c4 files without issue, but when it got to the views I received the output below. I'm unable to find any additional useful information. Any idea what that initRandomDevice is about? It just listed that same alert multiple times per view and then finished. 

![image](https://github.com/likec4/likec4/assets/136729466/fa774e42-d6b1-46ec-9b0b-c1c15ce4ba62)

The build agent is running Ubuntu
![image](https://github.com/likec4/likec4/assets/136729466/645919d2-85ad-42b4-8664-ad5227a8dc97)

**Comment by davydkov** [comment]
@ScottSlaughterBBNA Hey, thank you for reporting!

Yes, this message comes from [@hpcc-js/wasm graphviz](https://github.com/hpcc-systems/hpcc-js-wasm)

When I faced this issue I found at [release notes of state-machine-cat](https://github.com/sverweij/state-machine-cat/releases/tag/v11.0.1):

> For the release on npmjs we'll need to tweak the warning system on the cli a bit, still, as it turns out. On node 16 and 18 state-machine-cat now emits Aborted(initRandomDevice) message on stderr if the native graphviz dot isn't installed. On node 19 this message is absent, as it is in the browser. I suspect the hpcc-js/wasm/graphviz build, or the way state-machine-cat interacts with it (t.b.d.). The next release of state-machine-cat on npmjs will have either a fix or a workaround (e.g. a message?) to deal with this.

I have the same odd output with Node 18, but not with Node 20.

What node version do you use in your pipelines?

**Comment by ScottSlaughterBBNA** [comment]
Default for the agent. I'll have to take a look. I can upgrade it if needed. At least this gives me a place to start. Thanks.

**Comment by davydkov** [comment]
@ScottSlaughterBBNA can I close this one?

**Comment by ScottSlaughterBBNA** [comment]
I had some stuff come up and haven't been able to work on this. Go ahead and close it. I'll probably get back to it next week.

**Comment by ScottSlaughterBBNA** [comment]
@davydkov just to follow up, I verified that using node 20+ does resolve this issue. Thanks again.
