### ISSUE TITLE
CLI fails to export image on Windows  (with hacky fix)

### ISSUE THREAD

**Issue by mwardm** [likec4/likec4#280]
CLI doesn't work on Windows - there's a problem with backslashes in paths, 
When you write the file locations out to the puppeteer-script.js, the '\' characters aren't escaped and so they vanish when you execute the scripts.
E.g. the console log shows...
```
Prepare temporary node project...
exists: C:\Users\mike\AppData\Local\Temp\likec4-export\package-lock.json


Puppeteer scripts:
  C:\Users\mike\AppData\Local\Temp\likec4-export\puppeteer-page.js
  C:\Users\mike\AppData\Local\Temp\likec4-export\puppeteer-script.js


 Run export script...
  $ cd C:\Users\mike\AppData\Local\Temp\likec4-export
  $ node puppeteer-script.js


Launch puppeteer...
Load puppeteer-page...
node:fs:603
  handleErrorFromBinding(ctx);
  ^

Error: ENOENT: no such file or directory, open 'C:UsersmikeAppDataLocalTemplikec4-exportpuppeteer-page.js'
    at Object.openSync (node:fs:603:3)
    at readFileSync (node:fs:471:35)
    at C:\Users\mike\AppData\Local\Temp\likec4-export\puppeteer-script.js:65:14
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5) {
  errno: -4058,
  syscall: 'open',
  code: 'ENOENT',
  path: 'C:UsersmikeAppDataLocalTemplikec4-exportpuppeteer-page.js'
}
```

My Node and Javascript skills are years out of date but I managed to get the export working by finding what I assume is the locally-compiled cli.js file and amending in a couple of places.
In your source, it looks like my [hacky] changes were equivalent to...
a) Adding the line `puppeteerPageJSPath = puppeteerPageJSPath.replaceAll("\\","\\\\");` after line 37 in export-script-generator.ts.  (That was line 71231 in the generated cli.js.)
b) Adding `.replaceAll("\\","\\\\")` to the end of line 143 in export-script-generator.ts.
(That was [now] line 71344 in the generated cli.js.)

You'll know much better than I do how to fix the issue properly but the above should give any Windows users a fighting chance in the meantime :-)

Thanks for the pretty pictures!

Mike.

**Comment by davydkov** [comment]
Hi @mwardm!
[v0.34.0](https://github.com/likec4/likec4/releases/tag/v0.34.0) should fix "paths" on Windows.
Could you let me know if the issue has indeed been resolved?

**Comment by mwardm** [comment]
Windows path issue confirmed fixed , @davydkov .  Thanks!
