### ISSUE TITLE
Exported diagrams background needs to be transparent

### ISSUE THREAD

**Issue by ThePlenkov** [likec4/likec4#285]
Hi! Currently export command exports documents only in a dark theme and that creates problem with pasting these documents into another documents ( like wiki or Google Docs ).  Usually those tools use light background and it images generated with a dark background look weird. Ideally it should be transparent background for png diagram. Do you think is possible? Thanks!

**Comment by ThePlenkov** [comment]
After digging a little bit down i see now that the issue is caused by the puppeter itself. There are issue describing this problem:
- https://stackoverflow.com/questions/55105958/puppeteer-saved-png-is-not-transparent
- https://github.com/puppeteer/puppeteer/issues/4152
- https://github.com/puppeteer/puppeteer/issues/2035

Among possible solutions are:
- Downgrading to  1.1.0  ( which is not an option )
- [Using transparent body](https://github.com/puppeteer/puppeteer/issues/4152#issuecomment-917685384)
- [Using jpeg format instead of png](https://stackoverflow.com/a/67304648) ( interesting! )

**Comment by ThePlenkov** [comment]
ok type JPEG doesn;'t solve the issue fully

**Comment by ThePlenkov** [comment]
![image](https://github.com/likec4/likec4/assets/6381507/0cb29d47-49e0-4078-b587-cb21efeb657b)

**Comment by ThePlenkov** [comment]
i have tried transapent background solution and it works better, but it looks like theming support is needed anyway. Texts are too light now

![image](https://github.com/likec4/likec4/assets/6381507/10d2efa1-34b5-4e97-a6fc-bb70c32e1b76)

**Comment by davydkov** [comment]
Thank you, @ThePlenkov, impressive deep-dive 🤿 
Would you mind sharing your results as PR?

I see it as an option for CLI, but maybe you have a better idea, as it seems you already solved your use case.

**Comment by axelthas** [comment]
I want to second this feature request. I would love to have the means to export the diagrams on a white background (or transparent) so that it will look nice in documents like Google Docs. But as @ThePlenkov mentions, the colour scheme is not really fit to be displayed on a white background. A light colour theme is the solution for that.

**Comment by davydkov** [comment]
I switched to Playwright in CLI [`likec4`](https://github.com/likec4/likec4/tree/main/packages/likec4), and images are transparent now.
