### ISSUE TITLE
Possibility of relationship customization

### ISSUE THREAD

**Issue by MoBoo** [likec4/likec4#342]
Allow customization of the relationship edge, e.g. define color, line style and arrow head.
This would be useful to visualize different kinds of relationships.

This will require an extension of the language itself to allow adding additional information to a relation:
`componentA -> componentB "<label>" "<color>" "<line style>" "<arrow head>"`
`componentA -> componentB "log in" "amber" ".." "|>"`

Colors can be chosen from the default theme (`blue`, `sky`, `amber`, etc.) or maybe even be custom defined by hex code (e.g. `#61b8ac`).
Linestyles may be on of `--` or `..`
Arrowheads may be one of `>`(default), `|>`, `*`, `o`
(Taken from http://mermaid.js.org/syntax/classDiagram.html#defining-relationship)

Hapy to help with coding, but i might require an introduction ^^

**Comment by davydkov** [comment]
Hi @MoBoo 

Thank you for your valuable suggestion. I completely agree that having the ability to customize relationships is crucial for expressing and visualizing different kinds of relationships. And this is on top of my backlog.

However, I think it would be helpful to define different relationship kinds at the specification part, like "async" or "command" (and give it a style) to make the process more efficient.

Like:
```
specification {

  relationship async {
     color green
     line dashed
     head solid_diamond 
     tail none
  }

}

model {

  service1 -[async]-> service2 "mutates data"

}
```

Another thought, via tags:

```
specification {

  tag async {
    // if tag applied to elements
    element {
      ....
    }

    // if applied to relationships
    relationship {
      color green
      line dashed
      head solid_diamond 
      tail none
    }
  }

}

model {

  service1 -> service2 "mutates data" #async

}
```

Both variants might also be used as view predicates.


What do you think about this?

> Happy to help with coding, but i might require an introduction ^^

Oh, I would appreciate that.
But I know the documentation for contributors needs to be included here. I am working on it.

And sure, let's have a call/chat for the introduction if you are really into it.
(send me an email to denis@davydkov.com)

**Comment by MoBoo** [comment]
I like your idea leveraging specification, blends better with the rest of the language.

Personally i like the syntax `-[async]->` more than using tags. Tags (for some reason i cannot name) seem more disconnected with the actual relationship.

**Comment by davydkov** [comment]
Still need to update `@likec4/diagrams`
