### ISSUE TITLE
element links not working

### ISSUE THREAD

**Issue by MrSmiler** [likec4/likec4#525]
I have tried using element links as in your [example](https://likec4.dev/docs/dsl/model/#element-links) in the documentation but I'm not able to use the links it does not show anything that indicates or act as link, I both tried it in playground and local server.

**Comment by davydkov** [comment]
@MrSmiler, I'm really sorry for the delay in my response – I was on a long holiday.
But I'm back now and ready to help you out.
Thanks so much for raising the issue – you were absolutely right that it hadn't been implemented.

I've gone ahead and added a button with a link.
You can check it out here:
https://template.likec4.dev/view/aws

Sure this is not ideal, but as a temporary solution might work.
What do you think?

**Comment by MrSmiler** [comment]
I saw it and that looks great to me and would solve my problem, by the way this tool has lots of potential, thank you for making it.

**Comment by davydkov** [comment]
@MrSmiler I'm so happy to hear that!
