### ISSUE TITLE
Relations with container elements are not rendered

### ISSUE THREAD

**Issue by artursgirons** [likec4/likec4#530]
This is also stated in [docs](https://likec4.dev/docs/dsl/views/)

> Limitation
Relations with container elements are not rendered yet. Working on it...

Example code where in view it would be expected to see 3x arrows, but ATM none is rendered (React)

```
specification {
  element component
}

model {
  c1 = component {
    c11 = component
  }

  c2 = component {
    c21 = component {
      c211 = component
    }
  }
  
  c1 -> c2
  c11 -> c21
  c211 -> c1
}

views {
  view index {
    include *, c1.*, c2.*, c2.c21.*
  }
}
```

Adding it hare just to have visibility on when this feature gets added.

Eagerly waiting for this feature 🙏

**Comment by davydkov** [comment]
@artursgirons Do you mind to try it out?

**Comment by artursgirons** [comment]
@davydkov THNK YOU 🎖️ , this addition to the system works great. I'll play with it more in depth in coming days and will let you know if there are some quirks that might make sense to mention.
