### ISSUE TITLE
Relationship "technology" should be supported

### ISSUE THREAD

**Issue by bytesbybrandon** [likec4/likec4#576]
In Structurizr, we can add a technology to relationships. This is especially effective when trying to show that things like `http`, `vpn`, `okta` or some secure connection is required.

**Comment by vedeja** [comment]
Yes, I use it all the time!

**Comment by pavelpykhtin** [comment]
Implementation could look like this:
```
specification {
      element component
    }
    model {
      component client1
      component client2
      component server

      client1 -> server 'uses' 'graphql'
      client2 -> server {
        technology 'graphql'
      }
    }
```

And on the frontend side technology could be shown under the main label:
```
___   uses  ___\
   [graphql]   /
```
or if no label specified:
```
-[graphql]->
```

@davydkov , what do you think?
