### ISSUE TITLE
Icon from `https://icons.terrastruct.com` for Amazon CloudFront throws error

### ISSUE THREAD

**Issue by bytesbybrandon** [likec4/likec4#577]
When using the icon:

https://icons.terrastruct.com/aws%2FNetworking%20&%20Content%20Delivery%2FAmazon-CloudFront.svg

There is an error rendering:

```
Error: ... <TD ALIGN="CENTER" HEIGHT="32"><IMG SRC="https://icons.terrastruct.com/aws%2FNetworking%20&%20Content%20Delivery%2FAmazon-CloudFront.svg" SCALE="TRUE"/> ...
```

This actually happens for all of the Amazon CloudFront icons.

**Comment by davydkov** [comment]
Hey @bytesbybrandon!

Thank you for reporting the issue.
I noticed that the `&` symbol in url is causing the problem.
I reproduced in #578 

https://github.com/likec4/likec4/blob/f1ce04ee56483b40588bb55702fe7f126cdb5a24/packages/layouts/src/graphviz/__fixtures__/index.ts#L13-L14

Looking for solution

**Comment by tylerhubert** [comment]
@davydkov , was this fixed or only reproduced?  I'm having the same issue with some other AWS images from terrastruct.  Specifically 
https://icons.terrastruct.com/aws%2FSecurity%2C%20Identity%2C%20&%20Compliance%2FAWS-Key-Management-Service.svg
and 
https://icons.terrastruct.com/aws%2FSecurity%2C%20Identity%2C%20&%20Compliance%2FAWS-Identity-and-Access-Management-IAM_Temporary-Security-Credential_light-bg.svg

**Comment by davydkov** [comment]
@tylerhubert can you try [0.60.3](https://github.com/likec4/likec4/releases/tag/v0.60.3)?

**Comment by tylerhubert** [comment]
@davydkov that fixed it, thank you!  Sorry I missed that I was a version behind.

**Comment by davydkov** [comment]
@tylerhubert you were correct, I patched quickly after your comment. Thanks 👍

**Comment by tylerhubert** [comment]
Thank you for the quick turn around!  This project is awesome.  I love the flexibility of the views and the ease of creating the diagrams.  I've been able to build out a lot of things in a short amount of time.
