### ISSUE TITLE
Fails to render or open (in dev/serve mode) for "big" diagrams. 

### ISSUE THREAD

**Issue by ghazi94** [likec4/likec4#591]
I seem to have hit the limit of relationships I can have in `likeC4` which is astonishingly a small number. I barely have 12 relationships in total, yet `likeC4` is crashing when building / serving the diagrams.

Here is the stack trace with more information

```
5:27:50 PM c4:vite INFO generating virtual:likec4/views
Failed attempt to layout with graphviz: Error: memory access out of bounds
    at t.layout (file:///.../projects/diagrams/likec4/payplat-ddd/node_modules/likec4/dist/cli/index.js:230:615930)
    at t.dot (file:///.../projects/diagrams/likec4/payplat-ddd/node_modules/likec4/dist/cli/index.js:230:616268)
    at dotLayoutFn (file:///.../projects/diagrams/likec4/payplat-ddd/node_modules/likec4/dist/cli/index.js:223:699)
    at uD.attempt (file:///.../projects/diagrams/likec4/payplat-ddd/node_modules/likec4/dist/cli/index.js:230:618223)
    at async file:///.../projects/diagrams/likec4/payplat-ddd/node_modules/likec4/dist/cli/index.js:230:618033

```

I can also provide the source for the diagrams if it helps.

**Comment by davydkov** [comment]
Hey @ghazi9,

Thank you for reporting. 
I'm happy to assist you with it. 

I performed stress tests on a model consisting of 1000 elements and 10k relationships, and although the performance degraded, it still worked.
I'm curious about what is causing the memory issue you are experiencing. It seems to be coming from graphviz wasm. Can you try using binaries instead? 

You can use the `--use-dot-bin` option in cli. 

And can you share your model? (denis@davydkov.com)

**Comment by ghazi94** [comment]
Thank you very much for the quick reply!

I will try it out with the `--use-dot-bin` option to check.

Meanwhile, this is the source model: https://drive.google.com/drive/folders/1z98B8D8eUbKVB3kvI3YxcWLfjWpwv-4j?usp=sharing

You can reproduce the error by uncommenting the bottom 2 lines in the file `r_0_rel_flow.c4`

<img width="1084" alt="image" src="https://github.com/likec4/likec4/assets/13150349/7ce31f08-89dc-4e43-90a3-f774bf852b10">

**Comment by ghazi94** [comment]
The issue is resolved by using the `--use-dot-bin` arg. Thanks for the tip!
