### ISSUE TITLE
[Feature Request] Allow exclude (and include) for tagged relationships too

### ISSUE THREAD

**Issue by ghazi94** [likec4/likec4#593]
Currently, the exclude (or include) keyword for tags are only supported for kind `element`. For example,

```
exclude element.tag == #my_tag
```

It would be very useful to exclude certain relationships (graph edges) in views by referencing their tags. Something like:

```
exclude relationship.tag == #my_tag
```

If relationships could be assigned to variables, the same functionality could be achieved (instead of using tags). For example:

```
model {
    rel1 = a -> b 'some relationship 1'
}
```

```
exlcude rel1
```

**Comment by davydkov** [comment]
`where` in [1.7.0](https://github.com/likec4/likec4/releases/tag/v1.7.0)

[Documention](https://likec4.dev/dsl/views/#filter)
