### ISSUE TITLE
link property for relationships

### ISSUE THREAD

**Issue by gparmeggiani** [likec4/likec4#612]
I use the `link` property to link to documentation pages of each module, which is great.

It would be useful to also allow relationships to have a `link` property, so that all the documentation regarding interfaces between components can be linked.

What do you think?

**Comment by yadanilov19** [comment]
that will be great!

**Comment by davydkov** [comment]
Yes indeed, nice idea, and quite cheap to implement.
I can add to DSL, but do not show on diagrams

I am working on 1.0 with diagrams based on react-flow and implement there
