### ISSUE TITLE
Timout error while exporting views to png

### ISSUE THREAD

**Issue by mcpride** [likec4/likec4#634]
## Environment

I use the `mcr.microsoft.com/playwright:v1.41.2-jammy` docker image with a global installation of the LikeC4 CLI.

## Issue description

When I export the views to png files with `likec4 export png -o ./public/assets/png`, then at first a lot of views will be sucessfully exported but later it comes to a TimoutError:

```
INFO export proxyAppView1 http://172.17.0.3:62001/export/proxyAppView1?padding=24
INFO export proxyAppView2 http://172.17.0.3:62001/export/proxyAppView2?padding=24
INFO export serviceAppViewDetail1 http://172.17.0.3:62001/export/serviceAppViewDetail1?padding=24
INFO export serviceAppViewDetail2 http://172.17.0.3:62001/export/serviceAppViewDetail2?padding=24
INFO export serviceAppViewDetail3 http://172.17.0.3:62001/export/serviceAppViewDetail3?padding=24
ERROR Error when taking screenshot: http://172.17.0.3:62001/export/authAppView1?padding=24
TimeoutError: page.screenshot: Timeout 10000ms exceeded.
Call log:
  - taking page screenshot
  -   disabled all CSS animations
ERROR Error when taking screenshot: http://172.17.0.3:62001/export/authAppView2?padding=24
TimeoutError: page.screenshot: Timeout 10000ms exceeded.
Call log:
  - taking page screenshot
  -   disabled all CSS animations
  - waiting for fonts to load...
  - fonts loaded
ERROR Error when taking screenshot: http://172.17.0.3:62001/export/configurationAppView2?padding=24
TimeoutError: page.screenshot: Timeout 10000ms exceeded.
Call log:
  - taking page screenshot
  -   disabled all CSS animations
ERROR Error when taking screenshot: http://172.17.0.3:62001/export/proxyAppView2?padding=24
TimeoutError: page.screenshot: Timeout 10000ms exceeded.
Call log:
  - taking page screenshot
  -   disabled all CSS animations
```

In a local windows environment with installed playwright the export succeeds!

**Comment by davydkov** [comment]
Hey @mcpride 

Thanks for your interest in the project and reporting issues. 

Can you check if you still have timeouts with [0.60.1](https://github.com/likec4/likec4/releases/tag/v0.60.1)?
and update to Playwright 1.42.1 (It is not related to the issue, but it's good to update anyway.)

**Comment by mcpride** [comment]
Thanks @davydkov, I tested it in our ci environment and it works without errors! 👍  

But it was needed to downgrade the version of the used Playwright image from `v1.41.2` to `v1.41.1` (mcr.microsoft.com/playwright:v1.42.1-jammy).

The behavior for the manual export to png in a Browser (Chrome, Mozilla) was not changed - it doesn't work for security reasons:
```
SecurityError: Failed to execute 'toBlob' on 'HTMLCanvasElement': Tainted canvases may not be exported.
```
As far as I know, this has to do with the CORS configuration.

**Comment by mcpride** [comment]
Hello @davydkov! 

Unfortunately, I had another timeout error today, but without canceling my ci job::

```
...
INFO /export/authAppScopeAndContextView
INFO /export/authAppLevel1ServerServiceView
ERROR failed on authAppLevel1ServerServiceView
TimeoutError: page.goto: Timeout 10000ms exceeded.
Call log:
  - navigating to "http://172.17.0.2:62001/export/authAppLevel1ServerServiceView", waiting until "load"
INFO /export/authAppLevel1AdministrationServiceView
INFO /export/authAppLevel2ServerServiceFrontendView
...
INFO exported 38 failed 1 in 3m 23.5s
INFO close chromium
INFO clean build outDir
INFO stop preview server
INFO ✓ export in 3m 35.5s
...
```

**Comment by davydkov** [comment]
I have no idea for now, as I don't encounter such an issue,
Can you share the diagram size (width/height) and how many nodes/edges there are?

As a workaround, in 0.60.2, I suggest retrying and configuring timeouts (probably shorter to fail-fast).

**Comment by mcpride** [comment]
Thank you, @davydkov, 
I think, a configurable timeout may help. Currently we have some peeks in our CI infrastructure - too much resource intensive running docker container instances in parallel.
The failed diagram itself isn't very complex, I will attach an anonymized picture of it.
The whole model and views count are a bit larger - separated in a lot of files - and it will will grow:

- 44 views
- 49 c4 files
- 
![View](https://github.com/likec4/likec4/assets/1053528/08a79a21-0e15-45d1-a71b-d2341437e1fd)
