### ISSUE TITLE
Icons do not render when expected in React app

### ISSUE THREAD

**Issue by jamesvl** [likec4/likec4#649]
I'm noticing icon rendering issues when running 0.60.3 locally vs. using the latest version of the VSCode plugin:

* icons from terrastruct (or other sources) mostly don't show up
  * this happens for multiple icons I've tried from S3, localhost server, or Terrastruct, but not all (see example) 
* if using the Preview in VSCode, those same icons *do* show up
  * but if I remove the `color` directive from the style, the VSCode previews also fails to show the icon

This occurs regardless of where I put the `style` block (in the view or the model).

### Screenshots
![snip_03-155118](https://github.com/likec4/likec4/assets/354570/f0962b08-8390-4668-ad1b-edf3bc9a9803)
![snip_03-155143](https://github.com/likec4/likec4/assets/354570/34f2e3a2-686a-4369-a081-c48f242390ee)

### Minimal Example

```
specification {
  element service
}
model {
  service ex_logo 'Example Missing Logo'
}
views {
  view ex_logo {
    include ex_logo
    style ex_logo {
      icon https://icons.terrastruct.com/essentials%2F092-network.svg
      // color line is required or VSCode also fails
      color gray
      // but this icon does work?
      // icon https://icons.terrastruct.com/infra%2F010-data-sharing.svg
    }
}
```

**Comment by davydkov** [comment]
Hi @jamesvl 

Thanks for reporting the issue.
Can you try [v0.60.4](https://github.com/likec4/likec4/releases/tag/v0.60.4)?

**Comment by jamesvl** [comment]
It does not, really.

I should have split it into two bugs; the first was related to the `color` directive affecting whether a logo gets rendered; this looks fix in the version you posted.

The actual bug I was trying to show is independent of color; most icons do not render at all. Here's a better example:

```
specification {
  element system
}

model {
  system ex_logo 'Example Missing Logo'
}

views {
  view ex_logo {
    include ex_logo

    style ex_logo {
      // this icon never renders in the npm version
      icon https://icons.terrastruct.com/essentials%2F092-network.svg

      // but this icon does...?
      // icon https://icons.terrastruct.com/infra%2F010-data-sharing.svg
    }
  }
}
```

**Comment by jamesvl** [comment]
This appears to be working normally as of the 1.2.x release; feel free to close this one out! :pray:
