### ISSUE TITLE
Sporadic build errors (graphviz problem?)

### ISSUE THREAD

**Issue by mcpride** [likec4/likec4#660]
Hi @davydkov,

unfortunately I have to report another sporadic problem while builing our model.  Sometimes it works, sometimes it hangs without error message or sometimes  there is an error message. The problem exists for the 0.60.* and for the 1.0.0-next* versions.

For example the error message for the 0.60.4 version looks like this after a `likec4 serve`:

```
14:36:44 c4:vite INFO generating virtual:likec4/views
Failed attempt to layout with graphviz: Error: memory access out of bounds
    at t.layout (file:///C:/Users/xxx/scoop/persist/nodejs/bin/node_modules/likec4/dist/cli/index.js:221:688150)        
    at t.dot (file:///C:/Users/xxx/scoop/persist/nodejs/bin/node_modules/likec4/dist/cli/index.js:221:689090)
    at dotLayoutFn (file:///C:/Users/xxx/scoop/persist/nodejs/bin/node_modules/likec4/dist/cli/index.js:213:727)        
    at hD.attempt (file:///C:/Users/xxx/scoop/persist/nodejs/bin/node_modules/likec4/dist/cli/index.js:221:691116)      
    at async file:///C:/Users/xxx/scoop/persist/nodejs/bin/node_modules/likec4/dist/cli/index.js:221:690866
Failed to layout with graphviz, retrying...
```

I reduced our model extremly to just a few resources and 1 file and anonymized it, so that I can publish it here for test!

[system-landscape.c4.txt](https://github.com/likec4/likec4/files/14970789/system-landscape.c4.txt)

I hope, you can help, I'm somewhat at a loss. :-(

**Comment by davydkov** [comment]
Hi @mcpride 

I am happy to help you.
The error comes from WASM-graphviz. I will investigate the cause tomorrow.

In the meantime, would you mind trying to use graphviz binary?

https://github.com/likec4/likec4/issues/534#issuecomment-1962286684

**Comment by davydkov** [comment]
… and vscode extension has a setting

**Comment by mcpride** [comment]
It seems, that the graphviz binary raises the same sporadic errors as the wasm. 

Something is wrong with these not very complex views. Our original project is large in the meantime and has over 70 views and there are no problems to build them - except these here.

**Comment by mcpride** [comment]
I tested it against the new version [v1.0.0-next.14](https://github.com/likec4/likec4/releases/tag/v1.0.0-next.14) and it looks good so far! It seems, this version solves the problem.
