### ISSUE TITLE
Could we allow deep-linking in GitHub Pages?

### ISSUE THREAD

**Issue by CrossEye** [likec4/likec4#661]
I'm quite new to LikeC4, and am very impressed.  We've been able to get a lot done in just a few days.

Everything is working well, with one exception.  I've posted our project to GitHub Pages, and it runs just fine, but we can't deep-link to the various views.  I'm assuming that this is because GH Pages sees this URL:

    https://github.my-enterprise.com/pages/group/proj/view/viewName

as pointing to the path `/pages/group/proj/view/viewName`, and finds nothing there.  It doesn't know to stop at `/pages/group/proj` to allow LikeC4 to handle `/view/viewName`.

Could we allow LikeC4 to manage -- behind a flag, perhaps -- URLs like many SPAs generate?:

    https://github.my-enterprise.com/pages/group/proj/#/view/viewName

Everything after the `#/` would be treated by LikeC4 just like the current paths are handled.

I see only one non-bot commit from anyone other than the main dev.  Do you take outside help?  And if so, could you point me in the general direction of the code that might need to be altered.  I'm plenty competent in JS, and can work in TS when absolutely necessary.  ( 😄 ).

**Comment by davydkov** [comment]
Hey @CrossEye

Am I correct that you are deploying to GitHub Pages from a repository that does not have a custom domain?
Do you set base [as here](https://github.com/likec4/example-cloud-system/blob/main/.github/workflows/pages.yml#L44) (with github action)?

```yml
- name: Build
  uses: likec4/actions@v1
  with:
    action: build
    output: dist
    base: "/pages/group/proj"
```

Or with CLI:

```
$ likec4 build --base '/pages/group/proj' .
```

---

>
>  Do you take outside help? 
>

Sure 🤩!!
For instance, @MoBoo did this #342

>
>  And if so, could you point me in the general direction of the code that might need to be altered.
>

Of course, reach me `denis@davydkov.com`

**Comment by CrossEye** [comment]
@ [davydkov](https://github.com/davydkov)
> Am I correct that you are deploying to GitHub Pages from a repository that does not have a custom domain?

Yes, you are.  This is Enterprise GitHub, behind corporate walls, where I've never tried to get a custom domain, and don't know if the company would even consider it.   But I will check it out.  I have personal stuff working on public GH Pages with custom domains, and it works like a charm.  But those are SPAs, where I don't have this issue.

> Do you set base [as here](https://github.com/likec4/example-cloud-system/blob/main/.github/workflows/pages.yml#L44) (with github action)?

Yes, I have something much like this:

> `$ likec4 build --base '/pages/group/proj' `

And the application is working fine.  I would like, though, to be able to share links directly to various views; GH Pages thinks such URLs are meant to link to more deeply nested files... which of course don't exist.

If I get everything working the way I would like, I will switch over to GH Actions, but for the moment, it's easy enough to run the build before I push.

>> Do you take outside help?

> Sure 🤩!!

Great!  I'll reach out to you directly.  Thank you.

**Comment by CrossEye** [comment]
Thank you very much for this fix!

**Comment by CrossEye** [comment]
This has been working well for us.  Thank you.

I noticed one spot where the hash-bang didn't seem to get used.  `Share > Embed Tab`.

I will see if I can find time to learn enough to offer a PR for this.  Thanks for all the great work.

**Comment by davydkov** [comment]
@CrossEye PRs are always welcome!

Quick start:

```
cd packages/likec4
yarn turbo:build
yarn dev
```

Sources are at `packages/likec4/app/src`
