### ISSUE TITLE
[Feature Request] Add theme choice (dark/light) to CLI build command

### ISSUE THREAD

**Issue by folladore** [likec4/likec4#685]
First of all congratulations and thank you for this great tool, that I am still discovering.

I would like to use the CLI build command to generate images and include them in PDF documents with white backgrounds.
For this use case I need a light theme to be used during "assets" generation.

As the light theme is already available when "serving"  with `likec4 serve` it could perhaps be an easy addition to the command line?

**Comment by davydkov** [comment]
Hi @folladore 

Thanks for your interest in the project!

What CLI version do you use?

**Comment by folladore** [comment]
Hello @davydkov,

thank you for your quick answer.
At my side, both 0.60.4 and 1.0.0-rc.1 exports png to dark theme.

Perhaps it depends on my setup?
As I am not used to node environments I'll describe here my installation that may be weird or unusual (don't hesitate to tell me):

I am on Debian 12.
To avoid granting root access to node applications I have installed it with nvm (v0.37.2)
`wget -qO- https://raw.githubusercontent.com/nvm-sh/nvm/v0.37.2/install.sh | bash`
`source ~/.bashrc`
`nvm install node`

To try to resolve issues explained here after, I have "forced" node to lts/iron v20.12.2 instead of v22.0.0.

I have installed likec4 v0.60.4 globally with `npm install --global likec4`

At this time, the `likec4 serve` command worked like a charm but the `likec4 export` failed because of a ms-playwright error telling it doesn't find chrome.
In fact it looked for `/home/lfe/.cache/ms-playwright/chromium-1105/chrome-linux/chrome` but only chromium-1112 exists instead under this ms-playwright path.
I have workaround this by creating a soft link so that chromium-1105 is resolved to chromium-1112.

Later, while describing my model using likec4 v0.60.4, I have experienced memory errors during `likec4 serve` where node attempted to access illegal memory addresses. It was so frequent and annoying that it lead me to try 1.0.0-rc.1 which seems to fix these memory issues.

Concerning my environment and the export theme, I have a "Breeze-dark" theme on KDE 5.103.0 according to `kf5-config`
other information that may interest you are
`gsettings get org.gnome.desktop.interface gtk-theme` answers 'Breeze'
`gsettings get org.gnome.desktop.interface color-scheme` answers 'prefer-dark'

Please tell me, if you need other information to track down an issue.

I have noted 6555303 adds the theme argument to CLI, thanks for it!
However I am not able (yet) to use from source...
