### ISSUE TITLE
Blurry text when hovering over an element or relationship

### ISSUE THREAD

**Issue by davydkov** [likec4/likec4#749]
_Originally posted by @aelberg in https://github.com/likec4/likec4/issues/734#issuecomment-2134997927_

> Confirmed the text is sharp in version 1.1.1 
> However, at certain zoom levels when hovering over an element or relationship the text is blurry.  I see the same behavior in Chrome and Edge browsers.
> I tried with the example DSL from the getting started page (https://likec4.dev/docs/) and was not able to replicate the behavior.
> 
> 
> Sharp font (not hovered over): 
> ![likec4-1](https://github.com/likec4/likec4/assets/55560119/d3e5961e-62ce-4e99-9c0f-feb311993c7b)
> 
> Blurry (hovered over):
> ![likec4-2](https://github.com/likec4/likec4/assets/55560119/8f090f8e-de1c-4075-b4c5-43c916f90099)

**Comment by davydkov** [comment]
@aelberg Thanks for reporting, gonna check it.

Originally issue was due to https://github.com/xyflow/xyflow/issues/3282, and I temporary workaround it ("dirty", but have to wait for the xyflow's fix)

https://github.com/likec4/likec4/blob/08fd81d1d667a19742749d19d388dcbce49be80f/packages/diagram/src/xyflow/XYFlowEvents.tsx#L55-L59

Probably to address hovering issue I need to play with different values for scale

**Comment by aelberg** [comment]
Thank you for the update!  I noticed it can happen at some zoom levels even without hovering as well. My resolution is 1920x1080.
The temporary workaround is working well in most scenarios and I'm able to zoom in or out a bit to avoid the issue for now as well.
