### ISSUE TITLE
Enable/Disable animations

### ISSUE THREAD

**Issue by davydkov** [likec4/likec4#773]
>  Most of my diagrams have 10-20 elements and even at 10 you begin to see degradation in performance, making zooming, click to highlight, and hovering quite slow. I have experimented a bit to try and disable the animations altogether, with some kind of improved but unsatisfying result. Also with the UX more plain and boring. Is 10 elements in a view stretching the limit? Can we optimize the rendering? Is an option to disable animation a bad idea?
>
> As discussed in #600, v1 did improve things to the layout in general but overall the slow animations still haunt me.

_Originally posted by @vedeja in https://github.com/likec4/likec4/discussions/770_

**Comment by davydkov** [comment]
Hi @vedeja

Could you try v1.3.0?

**Comment by SESTVED1** [comment]
@davydkov I will, thanks!

**Comment by vedeja** [comment]
@davydkov It is perhaps a bit better for me, but not in Safari unfortunately.

**Comment by davydkov** [comment]
@vedeja macos or iOS? How many elements/levels are on the diagram?

**Comment by vedeja** [comment]
MacOS and 20 elements. The hover effect on relationships starts almost immediately, but the delay before the elements "grow" on hover is may main issue.

**Comment by vedeja** [comment]
Generally though @davydkov, viewed from a Windows machine on Chrome, it is a great improvement from pre 1.0.0!
