### ISSUE TITLE
Issue generating React Component when using icons

### ISSUE THREAD

**Issue by Manu2524** [likec4/likec4#909]
Hello,

First of all, great job on LikeC4! I am using it within a Docusaurus app, and embedding LikeC4 diagrams as react components within MDX file. 

I'm getting an error when generating a react component using the CLI. This issue occurs when I specify an icon within my spec or directly within a model. 

For example:
```
store = storage 'Store' {
      icon tech:postgresql
      description 'A Postgres store'
}
```
I have also tried the following (same issue):
```
store = storage 'Store' {
      description 'A Postgres store'
      style {
         icon tech:postgresql
      }
    }
```

The command I run is the following
_npx likec4 gen react directory_name_

The error I am getting is the following:
```
Line 22: Expecting token of type '}' but found icon.
     Line 22: Expecting: one of these possible Token sequences:
  1. [this]
  2. [it]
  3. [->]
  4. [-[]
  5. [Dot]
  6. [IdTerminal, StickyDot]
  7. [IdTerminal, ->]
```

It looks like icon is not support within the react component generator. 

I have no issues with the generator unless I start using icons.

**Comment by davydkov** [comment]
@Manu2524
What CLI version do you use?

**Comment by Manu2524** [comment]
@davydkov - I use 1.4.0

**Comment by davydkov** [comment]
@Manu2524 Can you try with `1.7.2`?

**Comment by Manu2524** [comment]
@davydkov - it seems to work. I should have checked before posting an issue. Thanks for the support.

**Comment by wgordon17** [comment]
@Manu2524 apologies for the unrelated question, but _how_ are you using this with Docusaurus? Any chance you have an example...I can't get it to work to save my life 😅
