### ISSUE TITLE
Parent-relations can't contain comments

### ISSUE THREAD

**Issue by lars-solberg** [likec4/likec4#911]
Comments on child->child relations works great, but if you try to make a comment where you don't comment on the child relation, like the example below; nothing happens.

I'm not sure if this is a bug or if it is not implemented

```
specification {
  element node
}

model {
  node a1
  node a2
  a1 -> a2 "comment included"

  node b1 {
    node b11
    node b12
  }
  node b2 {
    node b21
    node b22
  }
  b1 -> b2 "comment not included"
}

views {
  view index {
    include *
    include b1, b1.*, b2, b2.*
  }
}
```

I checked the generated DOM, and the element for the b* comment above was not even in there.

![Screenshot 2024-08-16 at 15 15 31](https://github.com/user-attachments/assets/f909ca3a-f892-4da2-ae78-f4319710ee52)

**Comment by davydkov** [comment]
Thank you @lars-solberg for reporting.

After investigation, I filed issue to graphviz library
https://gitlab.com/graphviz/graphviz/-/issues/2592

I put this on hold until they response.
