### ISSUE TITLE
What is the recommended way to work with architecture described in likec4 model?

### ISSUE THREAD

**Issue by pavelpykhtin** [likec4/likec4#915]
Hi!

First of all, thank you for the really cool tool!

I would like to use likec4 model not only for diagrams but also in other scenarios:
- build new artifacts based on this model (lists of components, data flows, threat model etc.)
- validate the implementation against the architecture

I see at least two options here:
- implement exporter into some intermediate format (e.g., json) and then parse it in another tool
- include @likec4/language-server itself into a tool as it already emits parsed model

I've tried the second option, but it looks like @likec4/language-server can not be used in this way. Is this intended or just because there were no such use case?
The second option might be more robust because it uses public contract (intermediate format) and does not rely on the internal implementation of the language-server component. But it requires some additional steps (export) and some amount of work to implement parser.

Which option is better aligns with the likec4 development plans?

**Comment by davydkov** [comment]
Hey @pavelpykhtin 

Agree, the second option is more robust, and I would say approx middle-or-end Sep it will be possible.

For now I suggest go with first option and [export to JSON](https://likec4.dev/tooling/cli/#export-to-json).

But what I find interesting, is that I had kind of same idea - an interface that allows extract some artifacts, like openapi specs, schemas....

With some imagination:

```
specification {
  element table
  element column

  relationship foreignKey
}

model {

  table users {
    column id
    column name
  }

  table sessions {
    column id
    column userId

    userId .foreignKey users.id
  }

}


```

But there is no convenient API to work with such model.
Internally there is some [LikeC4ModelGraph](https://github.com/likec4/likec4/blob/main/packages/language-server/src/model-graph/LikeC4ModelGraph.ts), it is kinda utility for computing views.

I think I come with something like this, but allowing to traverse the model.

Can you share your use case and what your want to achieve? Here or denis@davydkov.com

**Comment by pavelpykhtin** [comment]
The goal of my current project is to integrate about 10 existing products of our company. Those products are developed by theirs own teams. I'm responsible for designing integration interactions and APIs which will enable those interactions.

Currently, I use structurizr. I annotate relationship with the following attributes:
- dataType - comma separated list of data types, transferred during the interaction
- dataflowDirection - forward|reverse|bidirectional. Direction of data flow relative to direction of relationship.
- dataflowId - unique identifier of the relationship/data flow
- protection - security measures applied to interaction
- messageSize - average size of the message transferred during the interaction
- messagePerMinute - average message rate for the interaction
Also, I have an 'extension' to structurizr workspace: json file with the list of trust boundaries. Technically, it's a tree whose leaves are users and products or their components.

So far, I have the following set of artifacts:
- Diagrams for main use cases (views with elements and relationships filtered by tag of the scenario)
- System Context diagrams for each product
- CSV list of interactions between products with corresponding data types, message size and message rate. I tried to use it to ensure that we have non-functional requirements for each interaction between products. Later it can be used to provide
- Dataflow diagram for the threat modeling. The diagram depicts main interactors (roles and components), data being sent between them, trust boundaries which those data cross and security measures applied to protect the during the transfer or storing. I'm exporting views for main use cases to drawio. During the export, dataType and dataflowId attributes are used as labels for relationships. Direction of relationship is modified according to the value of the dataflowDirection attribute.
- List of interactors for the threat modeling. CSV list of users and software systems with descriptions and incoming/outgoing data. Just a part of internal template for threat model document.
- CSV list of data flows for the threat modeling. Another presentation of dataflow diagram. Uses mostly the same attributes.
- CSV list of trust boundaries

Summarizing everything above, I need to be able:
- to traverse through all elements, relationships and views
- to traverse through elements, relationships of the view
- to annotate model with custom attributes (working on PR for this right now)
- to read attributes of the elements and relationships

Sorry for too many details. Just want to be sure that I provided enough context.

**Comment by davydkov** [comment]
@pavelpykhtin 

I am working on API. Basically looks like:

```js
import { LikeC4 } from "likec4"

const likec4 = await LikeC4.fromWorkspace(`/home/projects/`)

const model = likec4.model()

model
  .element('cloud.backend.api')
  .incoming() // relationships incoming to the element
  .filter(r => r.tags.includes('http')) // filter by tags
  .map(r => r.source) // get source elements

```

Can you take a look?

```
npm install likec4@next
```

Docs in progress - https://1e8152fb.likec4-docs-astro.pages.dev/tooling/model-api/

**Comment by pavelpykhtin** [comment]
@davydkov 

It seems pretty good! It is easy to use and covers most of my cases! The only case which is not covered is diagram export (or I just can't find a way to export coordinates).

I noticed some strange behavior on view.connections(). Given the model is defined as:
```
specification {
    element system
    element component
}
model {
  system sys1
  system sys2 {
    component c1
    component c2
  }

  sys1 -> sys2 "Do A, Do B"
  sys1 -> sys2.c1 "Do A"
  sys1 -> sys2.c2 "Do b"
}
views {
    view index {
        include *
    }
}
```

connections() method will return all three connections - 'Do A, Do B', 'Do A', 'Do B'. I expect that only connections included in view will be returned. In most cases it's easy to workaround, so it's not a critical problem.

**Comment by simonwfarrow** [comment]
> @pavelpykhtin
> 
> I am working on API. Basically looks like:
> 
> ```js
> import { LikeC4 } from "likec4"
> 
> const likec4 = await LikeC4.fromWorkspace(`/home/projects/`)
> 
> const model = likec4.model()
> 
> model
>   .element('cloud.backend.api')
>   .incoming() // relationships incoming to the element
>   .filter(r => r.tags.includes('http')) // filter by tags
>   .map(r => r.source) // get source elements
> ```
> 
> Can you take a look?
> 
> ```
> npm install likec4@next
> ```
> 
> Docs in progress - https://1e8152fb.likec4-docs-astro.pages.dev/tooling/model-api/

I have been using this next release and the API, its really useful to be able to navigate the model in code and link to external artefacts.
One thing I would like be able to do is detect interaction on the generated React LikeC4View class, such as knowing when a user clicks on a relationship. I tried using a mouse event handler but this only exposes the svg elements. Is there a way to listen to events such as nodeClick, relationshipClick etc. ?

**Comment by davydkov** [comment]
@simonwfarrow Hmm, interesting! I never thought it might be needed.

The underlying LikeC4Diagram component already has these handlers. 
https://github.com/likec4/likec4/blob/5c6e236c653a3525029cc5b2833bf2681c4440b3/packages/diagram/src/LikeC4Diagram.props.ts#L241-L256

The generated React `LikeC4View` essentially wraps `LikeC4Diagram`, but it doesn't expose its interface. It is generated from [this source](https://github.com/likec4/likec4/blob/main/packages/likec4/app/react/likec4.tsx)

As you can see, it renders [LikeC4ViewElement](https://github.com/likec4/likec4/blob/main/packages/likec4/app/react/components/LikeC4ViewElement.tsx) from `likec4/react` (which renders [`LikeC4Diagram`](https://github.com/likec4/likec4/blob/main/packages/diagram/src/LikeC4Diagram.tsx) in the shadow DOM). Onclick opens a dialog, [LikeC4Browser](https://github.com/likec4/likec4/blob/main/packages/likec4/app/react/components/LikeC4Browser.tsx), which is also in the shadow DOM but fullscreen.

What do you think—if you can use the generic LikeC4Diagram from likec4/react (but wrapped in shadow DOM) — would that fulfill your needs?

It might look something like:

```tsx
import { GenericLikeC4Diagram } from `likec4/react`
import { LikeC4Views, RenderIcon } from `./generated`

const App = () => {
  const view = LikeC4Views['view-id']
  return <div className="your-container">
    <GenericLikeC4Diagram
      view={view}
      renderIcon={RenderIcon}
      onNodeClick=(({element, event}) => ...)
    />
  </div>
}

```

**Comment by simonwfarrow** [comment]
Yes those handlers look ideal, I think I can get access to the underlying relationship properties via the ComputedEdge class that is extended by DiagramEdge ? https://github.com/likec4/likec4/blob/8ab164d195265e9ad3d9439587a9e1cb472e4f20/packages/core/src/types/view.ts#L222C18-L222C30

Would this replace the need for the generated LikeC4View? Instead displaying the view via the model API?

**Comment by davydkov** [comment]
@simonwfarrow Can you give it a shot?

https://likec4.dev/tooling/codegen/#reactlikec4

**Comment by simonwfarrow** [comment]
> @simonwfarrow Can you give it a shot?
> 
> https://likec4.dev/tooling/codegen/#reactlikec4

Great will do, thanks!

**Comment by simonwfarrow** [comment]
@davydkov I am probably doing something daft, but using ReactLikeC4 the rendering of diagram does not display/size correctly.

Comparing LikeC4View and ReactLikeC4 DOMs side by side it seems the aspect-ratio is not set on the ReactLikeC4 rendering which causes the viewport to be sized incorrectly I think.

LikeC4View:
![Screenshot 2024-09-12 at 16 45 02](https://github.com/user-attachments/assets/36603352-de28-48c7-9de9-070d62f36705)

ReactC4View:
![Screenshot 2024-09-12 at 16 44 55](https://github.com/user-attachments/assets/499bddd7-fe00-4e8b-a65a-806b79860135)

If I manually set the aspect-ratio on the ReactC4View element the diagram shows.

**Comment by simonwfarrow** [comment]
The display aside though, the handlers are working great! 

Love the fact I can click on an egde, get the relationship ids from the array and then look them up in the model.
Very useful for when there are multiple relationships and you see the [..] icon.

**Comment by davydkov** [comment]
@simonwfarrow you sure you don't have keepAspectRatio=false?

```tsx
<ReactLikeC4
  viewId="index"
  keepAspectRatio
  />
```

keepAspectRatio is true by default:

https://github.com/likec4/likec4/blob/df785c0dc373f32ce1cc9d6651af4af54df8ff88/packages/likec4/app/react/components/ReactLikeC4.tsx#L50-L70


> Very useful for when there are multiple relationships and you see the [..] icon.

This one is on my backlog

**Comment by simonwfarrow** [comment]
> @simonwfarrow you sure you don't have keepAspectRatio=false?

Doh! Yes that's exactly what I was doing - many thanks!
