### ISSUE TITLE
In the new version 1.8.0 there is a timeout when building (--use-dot)

### ISSUE THREAD

**Issue by viktorgusev1984** [likec4/likec4#959]
In the new version 1.8.0 there is a timeout when building use binary 
cli command : likec4 build --use-dot

trace:
transforming (57) ../../../react-dom/index.js[error] [BinaryGraphvizLayouter.layout] 'dot -Tjson -y' nothing returned and failed: 
12:04:18 PM c4:build INFO ✓ 67 modules transformed.
12:04:18 PM c4:build ERROR x Build failed in 5.22s
[vite-plugin-likec4] Could not load likec4-plugin/overview-graph.js (imported by node_modules/likec4/dist/__app__/src/main.js): Command timed out after 5000 milliseconds: dot -Tjson -y
    at E7 (file:///Users/v.n.gusev/Documents/code/architecture/node_modules/likec4/dist/cli/index.mjs:1193:1983)
    at pg (file:///Users/v.n.gusev/Documents/code/architecture/node_modules/likec4/dist/cli/index.mjs:1219:1346)
    at wye (file:///Users/v.n.gusev/Documents/code/architecture/node_modules/likec4/dist/cli/index.mjs:1226:37970)
    at xye (file:///Users/v.n.gusev/Documents/code/architecture/node_modules/likec4/dist/cli/index.mjs:1226:37690)
    at process.processTicksAndRejections (node:internal/process/task_queues:95:5)
    at async file:///Users/v.n.gusev/Documents/code/architecture/node_modules/likec4/dist/cli/index.mjs:1231:163 {
  shortMessage: 'Command timed out after 5000 milliseconds: dot -Tjson -y',
  command: 'dot -Tjson -y',
  escapedCommand: 'dot -Tjson -y',
  cwd: '/Users/v.n.gusev/Documents/code/architecture',
  durationMs: 5005.252,
  failed: true,
  timedOut: true,
  isCanceled: false,
  isGracefullyCanceled: false,
  isTerminated: true,
  isMaxBuffer: false,
  isForcefullyTerminated: false,
  signal: 'SIGTERM',
  signalDescription: 'Termination',
  stdout: '',
  stderr: '',
  stdio: [ undefined, '', '' ],
  ipcOutput: [],
  pipedFrom: [],
  code: 'PLUGIN_ERROR',
  plugin: 'vite-plugin-likec4',
  hook: 'load',
  

using command cli likec4 codegen react --use-dot  it builds without problems

**Comment by davydkov** [comment]
Thank you for the report, @viktorgusev1984.

I tried to reproduce the issue but without success. I hope the problem occurs only when the overview graph is used. In version 1.8.0, it was always used. I have fixed this; it is no longer included in the final build unless --use-overview is set.

And I increased timeouts. Sure, better to make it configurable, but lets see how it goes now.

**Comment by viktorgusev1984** [comment]
@davydkov Hi. I checked. It compiles without errors. Thank you  for the quick fix.
