### ISSUE TITLE
Relative links are translated into undeployable file:// URLs

### ISSUE THREAD

**Issue by phlash** [likec4/likec4#978]
Hi again, when building a static website, I find that relative `link` properties are translated into full URLs using the `file://` scheme which is of course no good when deployed.

 * Is there any reason to touch relative `link` properties at all (I was assuming my link would be emitted unmolested)?
 * If there is a reason to translate to full URLs, then should this use the `--base[-url]` parameter as supplied to `build` command?

Many thanks, Phil.

**Comment by davydkov** [comment]
Hey @phlash 

Thank you for reporting

> Is there any reason to touch relative link properties at all (I was assuming my link would be emitted unmolested)?

Indeed, it should be emitted untouched. This was done to meet the needs of my project. Now, it emits a separate relative field, which is relative to the workspace root.
